trigger:
  batch: true
  branches:
    include:
      - "*"

pr: none

variables:
- group: Docker Shared variables
- group: APPLY - Shared Variables
- name: imageName
  value: 'apply-for-postgraduate-teacher-training'
- name: debug
  value: true
- name: deployOnly
  value: false

stages:
- stage: build_release
  displayName: 'Build Release'
  variables:
  - group: APPLY - ENV - QA
  jobs:
  - job: build_docker_image
    displayName: 'Build Docker Image'
    condition: eq(variables['deployOnly'], false)
    pool:
      vmImage: 'Ubuntu-16.04'

    variables:
    - name: system.debug
      value: $(debug)

    steps:
    - script: | 
        echo '##vso[task.setvariable variable=compose_file]docker-compose.yml:docker-compose.azure.yml'
        docker_path=$(dockerHubUsername)/$(imageName)
        echo "##vso[task.setvariable variable=docker_path;]$docker_path"
      displayName: 'Configure build environment'

    - script: docker pull $(docker_path):build || true
      displayName: 'Pull cached intermediate Docker images'

    - script: make build
      displayName: 'Build Docker image'
      env:
        dockerHubUsername: $(dockerHubUsername)
        dockerHubImageName: $(imageName)
        railsSecretKeyBase: $(railsSecretKeyBase)
        RAILS_ENV: test
        GOVUK_NOTIFY_API_KEY: $(govukNotifyAPIKey)
        AUTHORISED_HOSTS: $(authorisedHosts)
        FIND_BASE_URL: $(findBaseUrl)
        GOVUK_NOTIFY_CALLBACK_API_KEY: $(govukNotifyCallbackAPIKey)
        SANDBOX: $(sandbox)

    - script: |
        mkdir $(System.DefaultWorkingDirectory)/docker_images
        docker save $(dockerHubUsername)/$(imageName) | gzip > $(System.DefaultWorkingDirectory)/docker_images/$(imageName)_images.tar.gz
        docker images $(dockerHubUsername)/$(imageName) | sed 1d | awk '{print $1 " " $2 " " $3}' > $(System.DefaultWorkingDirectory)/docker_images/images_manifest.txt
      displayName: 'Export Docker image'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Docker image artifact'
      inputs:
        path: '$(System.DefaultWorkingDirectory)/docker_images/'
        artifactName: 'docker_artifacts' 

  
- stage: test_release
  displayName: 'Test & Publish Release'
  dependsOn: build_release
  variables:
  - group: APPLY - ENV - QA
  jobs:
  - job: test_docker_image_batch_1
    displayName: 'Test Docker Image - Rubocop, Cucumber & Brakeman'
    condition: and(succeeded(), eq(variables['deployOnly'], false))
    pool:
      vmImage: 'Ubuntu-16.04'

    variables:
    - name: system.debug
      value: $(debug)

    steps:
    - script: |
        echo '##vso[task.setvariable variable=compose_file]docker-compose.yml:docker-compose.azure.yml'
      displayName: 'Configure environment'

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Docker image'
      inputs:
        artifact: 'docker_artifacts'

    - script: |
        docker load < $(Pipeline.Workspace)/$(imageName)_images.tar.gz
        while read REPOSITORY TAG IMAGE_ID
        do
           docker tag "$IMAGE_ID" "$REPOSITORY:$TAG"
        done < $(Pipeline.Workspace)/images_manifest.txt
        make az_setup
      displayName: 'Load Docker image & setup container'
      env:
        dockerHubUsername: $(dockerHubUsername)
        dockerHubImageName: $(imageName)
        railsSecretKeyBase: $(railsSecretKeyBase)
        RAILS_ENV: test
        GOVUK_NOTIFY_API_KEY: $(govukNotifyAPIKey)
        AUTHORISED_HOSTS: $(authorisedHosts)
        FIND_BASE_URL: $(findBaseUrl)
        GOVUK_NOTIFY_CALLBACK_API_KEY: $(govukNotifyCallbackAPIKey)
        SANDBOX: $(sandbox)

    - script: make ci.lint-ruby
      name: ci_lint_ruby
      displayName: 'Rubocop'
      env:
        dockerHubUsername: $(dockerHubUsername)
        dockerHubImageName: $(imageName)
        RAILS_ENV: test
        GOVUK_NOTIFY_API_KEY: $(govukNotifyAPIKey)
        AUTHORISED_HOSTS: $(authorisedHosts)
        FIND_BASE_URL: $(findBaseUrl)
        GOVUK_NOTIFY_CALLBACK_API_KEY: $(govukNotifyCallbackAPIKey)
        SANDBOX: $(sandbox)

    - script: |
        make ci.cucumber
        test_result=$?
        if [ "$test_result" == "0" ]
        then
          if [ $(find results/ -type f -name TEST*.xml | wc -l) -gt 0 ]
          then
            errors=0
            warnings=0

            for line in $(grep "^<testsuite " results/TEST*.xml)
            do
              if [[ $line == failure* ]]
              then
                test_failures=$(echo $line | cut -d '"' -f2)
                errors=$((errors+test_failures))
              fi
              if [[ $line == error* ]]
              then
                test_errors=$(echo $line | cut -d '"' -f2)
                errors=$((errors+test_errors))
              fi
              if [[ $line == skipped* ]]
              then
                test_skipped=$(echo $line | cut -d '"' -f2)
                warnings=$((warning+test_skipped))
              fi
            done

            if [ $errors -gt 0 ]
            then
              echo "##vso[task.logissue type=error]One or more cucumber tests failed."
              exit 1
            fi
            if [ $warnings -gt 0 ]
            then
              echo "##vso[task.logissue type=warning]One or more cucumber tests were skipped."
            fi

          else
            echo "##vso[task.logissue type=error]Cucumber test result files not found."
            exit 1
          fi
          exit 0
        else
          echo "##vso[task.logissue type=error]Cucumber test task exited abnormally."
          exit 1
        fi
      name: ci_cucumber
      displayName: 'Cucumber specs'
      env:
        dockerHubUsername: $(dockerHubUsername)
        dockerHubImageName: $(imageName)
        RAILS_ENV: test
        GOVUK_NOTIFY_API_KEY: $(govukNotifyAPIKey)
        AUTHORISED_HOSTS: $(authorisedHosts)
        FIND_BASE_URL: $(findBaseUrl)
        GOVUK_NOTIFY_CALLBACK_API_KEY: $(govukNotifyCallbackAPIKey)
        SANDBOX: $(sandbox)

    - script: make ci.brakeman
      name: ci_brakeman
      displayName: 'Brakeman'
      env:
        dockerHubUsername: $(dockerHubUsername)
        dockerHubImageName: $(imageName)
        RAILS_ENV: test
        GOVUK_NOTIFY_API_KEY: $(govukNotifyAPIKey)
        AUTHORISED_HOSTS: $(authorisedHosts)
        FIND_BASE_URL: $(findBaseUrl)
        GOVUK_NOTIFY_CALLBACK_API_KEY: $(govukNotifyCallbackAPIKey)
        SANDBOX: $(sandbox)

    - task: PublishTestResults@2
      displayName: 'Publish test results'
      inputs:
        testRunner: JUnit
        testResultsFiles: 'results/*.xml'


  - job: test_docker_image_batch_2
    displayName: 'Test Docker Image - RSpec'
    condition: and(succeeded(), eq(variables['deployOnly'], false))
    pool:
      vmImage: 'Ubuntu-16.04'

    variables:
    - name: system.debug
      value: $(debug)

    steps:
    - script: |
        echo '##vso[task.setvariable variable=compose_file]docker-compose.yml:docker-compose.azure.yml'
      displayName: 'Configure environment'

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Docker image'
      inputs:
        artifact: 'docker_artifacts'

    - script: |
        docker load < $(Pipeline.Workspace)/$(imageName)_images.tar.gz
        while read REPOSITORY TAG IMAGE_ID
        do
           docker tag "$IMAGE_ID" "$REPOSITORY:$TAG"
        done < $(Pipeline.Workspace)/images_manifest.txt
        make az_setup
      displayName: 'Load Docker image & setup container'
      env:
        dockerHubUsername: $(dockerHubUsername)
        dockerHubImageName: $(imageName)
        railsSecretKeyBase: $(railsSecretKeyBase)
        RAILS_ENV: test
        GOVUK_NOTIFY_API_KEY: $(govukNotifyAPIKey)
        AUTHORISED_HOSTS: $(authorisedHosts)
        FIND_BASE_URL: $(findBaseUrl)
        GOVUK_NOTIFY_CALLBACK_API_KEY: $(govukNotifyCallbackAPIKey)
        SANDBOX: $(sandbox)
    
    - script: |
        make ci.test
        test_result=$?
        if [ "$test_result" == "0" ]
        then
          if [ -f results/rspec-results.xml ]
          then
            if [ $(grep "^<testsuite name=\"rspec\"" results/rspec-results.xml | cut -d' ' -f5 | cut -d'"' -f2) -gt 0 ]
            then
              echo "##vso[task.logissue type=error]One or more rspec tests failed"
              exit 1
            fi
            if [ $(grep "^<testsuite name=\"rspec\"" results/rspec-results.xml | cut -d' ' -f4 | cut -d'"' -f2) -gt 0 ]
            then
              echo "##vso[task.logissue type=warning]One or more rspec tests were skipped"
              exit 1
            fi
          else
            echo "##vso[task.logissue type=error]rspec-results file not found."
            exit 1
          fi
          exit 0
        else
          echo "##vso[task.logissue type=error]Rspec test task exited abnormally."
          exit 1
        fi
      name: ci_test
      displayName: 'Execute tests'
      env:
        dockerHubUsername: $(dockerHubUsername)
        dockerHubImageName: $(imageName)
        RAILS_ENV: test
        GOVUK_NOTIFY_API_KEY: $(govukNotifyAPIKey)
        AUTHORISED_HOSTS: $(authorisedHosts)
        FIND_BASE_URL: $(findBaseUrl)
        GOVUK_NOTIFY_CALLBACK_API_KEY: $(govukNotifyCallbackAPIKey)
        SANDBOX: $(sandbox)

    - task: PublishTestResults@2
      displayName: 'Publish test results'
      inputs:
        testRunner: JUnit
        testResultsFiles: 'results/*.xml'


  - job: publish_docker_image
    displayName: 'Publish Docker Image'
    dependsOn: 
    - test_docker_image_batch_1
    - test_docker_image_batch_2
    condition: and(succeeded('test_docker_image_batch_1'), succeeded('test_docker_image_batch_2'))
    pool:
      vmImage: 'Ubuntu-16.04'

    variables:
    - name: system.debug
      value: $(debug)

    steps:
    - script: |
        GIT_SHORT_SHA=$(echo $(Build.SourceVersion) | cut -c 1-7)
        docker_path=$(dockerHubUsername)/$(imageName)
        echo "##vso[build.updatebuildnumber]$GIT_SHORT_SHA"
        echo "##vso[task.setvariable variable=docker_path;]$docker_path"
      displayName: 'Set version number'

    - task: DownloadPipelineArtifact@2
      displayName: 'Download Docker image'
      condition: and(succeeded(), eq(variables['deployOnly'], false))
      inputs:
        artifact: 'docker_artifacts'

    - script: |
        docker load < $(Pipeline.Workspace)/$(imageName)_images.tar.gz
        while read REPOSITORY TAG IMAGE_ID
        do
           docker tag "$IMAGE_ID" "$REPOSITORY:$TAG"
        done < $(Pipeline.Workspace)/images_manifest.txt
      displayName: 'Load Docker image'
      condition: and(succeeded(), eq(variables['deployOnly'], false))
    
    - task: Docker@1
      displayName: 'Tag image with current build number $(Build.BuildNumber)'
      condition: and(succeeded(), eq(variables['deployOnly'], false))
      inputs:
        command: Tag image
        imageName: "$(docker_path):latest"
        arguments: "$(docker_path):$(Build.BuildNumber)"

    - task: Docker@1
      displayName: 'Docker Hub login'
      condition: and(succeeded(), eq(variables['deployOnly'], false))
      inputs:
        command: "login"
        containerregistrytype: Container Registry
        dockerRegistryEndpoint: DfE Docker Hub

    - task: Docker@1
      displayName: 'Push tagged image'
      condition: and(succeeded(), eq(variables['deployOnly'], false))
      inputs:
        command: Push an image
        imageName: "$(docker_path):$(Build.BuildNumber)"

    - task: Docker@1
      displayName: 'Push tagged image (latest) if master or hotfix'
      condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/hotfix')))
      inputs:
        command: Push an image
        imageName: "$(docker_path):latest"

    - task: PublishPipelineArtifact@1
      displayName: 'Publish ARM template artifacts'
      inputs:
        path: '$(System.DefaultWorkingDirectory)/azure/'
        artifactName: 'arm_template'


- stage: deploy_qa
  displayName: 'Deploy - QA'
  dependsOn: test_release
  condition: and(succeeded('test_release'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  variables:
  - group: APPLY - ENV - QA
  jobs:
  - template: azure-pipelines-deploy-template.yml
    parameters:
      debug: $(debug)
      subscriptionPrefix: 's106'
      subscriptionName: 'Apply (106) - Dev'
      environment: 'qa'
      resourceEnvironmentName: 'd01'
      serviceName: 'apply'
      redisCacheSKU: 'Premium'
      redisCacheFamily: 'P'
      containerImageReference: '$(imageName):$(build.buildNumber)'
      keyVaultName: 's106d01-shared-kv-01'
      keyVaultResourceGroup: 's106d01-shared-rg'
      customHostName: '$(govukHostname)'
      databaseName: 'apply'
      databaseUsername: 'applyadm512'
      databasePassword: '$(databasePassword)'
      databaseStorageAutoGrow: 'disabled'
      databaseBackupRetentionDays: 7
      dockerhubUsername: '$(dockerHubUsername)'
      containerStartTimeLimit: '$(appServiceContainerTimeoutSeconds)'
      railsSecretKeyBase: '$(railsSecretKeyBase)'
      railsEnv: 'production'
      basicAuthEnabled: '$(basicAuthEnabled)'
      basicAuthUsername: '$(basicAuthUsername)'
      basicAuthPassword: '$(basicAuthPassword)'
      supportUsername: '$(supportUsername)'
      supportPassword: '$(supportPassword)'
      authorisedHosts: '$(authorisedHosts)'
      sentryDSN: '$(sentryDSN)'
      logstashEnable: '$(logstashEnable)'
      logstashRemote: '$(logstashRemote)'
      logstashHost: '$(logstashHost)'
      logstashPort: '$(logstashPort)'
      logstashSsl: '$(logstashSsl)'
      govukNotifyAPIKey: '$(govukNotifyAPIKey)'
      findBaseUrl: '$(findBaseUrl)'
      dfeSignInClientId: '$(dfeSignInClientId)'
      dfeSignInSecret: '$(dfeSignInSecret)'
      dfeSignInIssuer: '$(dfeSignInIssuer)'
      stateChangeSlackUrl: '$(stateChangeSlackUrl)'
      customAvailabilityMonitors: '$(customAvailabilityMonitors)'
      alertRecipientEmails: '$(alertRecipientEmails)'
      alertSlackChannel: '$(alertSlackChannel)'
      govukNotifyCallbackAPIKey: $(govukNotifyCallbackAPIKey)
      dsiApiUrl: '$(dsiApiUrl)'
      dsiApiSecret: '$(dsiApiSecret)'
      sandbox: '$(sandbox)'


- stage: deploy_devops
  displayName: 'Deploy - DevOps'
  dependsOn: test_release
  condition: and(succeeded('test_release'), eq(variables['Build.SourceBranchName'], variables.devDeployBranchNameOverride))
  variables:
  - group: APPLY - ENV - DevOps
  jobs:
  - template: azure-pipelines-deploy-template.yml
    parameters:
      debug: $(debug)
      subscriptionPrefix: 's106'
      subscriptionName: 'Apply (106) - Dev'
      environment: 'devops'
      resourceEnvironmentName: 'd02'
      serviceName: 'apply'
      ${{ if eq(variables['deployOnly'], true) }}:
        containerImageReference: '$(imageName):latest'
      ${{ if eq(variables['deployOnly'], false) }}:
        containerImageReference: '$(imageName):$(build.buildNumber)'
      keyVaultName: 's106d01-shared-kv-01'
      keyVaultResourceGroup: 's106d01-shared-rg'
      databaseName: 'apply'
      databaseUsername: 'applyadm512'
      databasePassword: '$(databasePassword)'
      databaseStorageAutoGrow: 'disabled'
      databaseBackupRetentionDays: 7
      dockerhubUsername: '$(dockerHubUsername)'
      containerStartTimeLimit: '$(appServiceContainerTimeoutSeconds)'
      railsSecretKeyBase: '$(railsSecretKeyBase)'
      railsEnv: 'production'
      basicAuthEnabled: '$(basicAuthEnabled)'
      basicAuthUsername: '$(basicAuthUsername)'
      basicAuthPassword: '$(basicAuthPassword)'
      supportUsername: '$(supportUsername)'
      supportPassword: '$(supportPassword)'
      authorisedHosts: '$(authorisedHosts)'
      sentryDSN: '$(sentryDSN)'
      logstashEnable: '$(logstashEnable)'
      logstashRemote: '$(logstashRemote)'
      logstashHost: '$(logstashHost)'
      logstashPort: '$(logstashPort)'
      logstashSsl: '$(logstashSsl)'
      govukNotifyAPIKey: '$(govukNotifyAPIKey)'
      findBaseUrl: '$(findBaseUrl)'
      dfeSignInClientId: '$(dfeSignInClientId)'
      dfeSignInSecret: '$(dfeSignInSecret)'
      dfeSignInIssuer: '$(dfeSignInIssuer)'
      stateChangeSlackUrl: '$(stateChangeSlackUrl)'
      customAvailabilityMonitors: '$(customAvailabilityMonitors)'
      alertRecipientEmails: '$(alertRecipientEmails)'
      alertSlackChannel: '$(alertSlackChannel)'
      govukNotifyCallbackAPIKey: '$(govukNotifyCallbackAPIKey)'
      dsiApiUrl: '$(dsiApiUrl)'
      dsiApiSecret: '$(dsiApiSecret)'
      sandbox: '$(sandbox)'
