trigger: none
pr: none

pool:
  vmImage: 'windows-2019'

parameters:
  - name: environment
    displayName: Environment
    type: string
    default: 'DevOps'
    values:
    - 'DevOps'
    - 'QA'
    - 'Staging'
    - 'Sandbox'
    - 'Production'

variables:
- group: 'APPLY - ENV - ${{ parameters.environment }}'
- name: buildCancelled
  value: false

jobs:
  - job: swap_staging_to_production
    displayName: Swap Staging Slot to Production in ${{ parameters.environment }}
    steps:
      - template: templates/swap-staging-production-slots.yml
        parameters:
          azureSubscription: $(azureSubscription)
          resourceGroup: $(resourceGroup)
          appService: $(appService)