---
questions:
  - label: Was it due to candidate behaviour?
    type: question
    answers:
    - label: 'Yes'
      type: radio
      questions:
      - label: What did the candidate do?
        type: question
        answers:
        - label: Didn't reply to our interview offer
          type: checkbox
        - label: Didn't attend interview
          type: checkbox
        - label: 'Other'
          type: checkbox
          questions:
          - label: Please give details
            type: question
            answers:
            - label: ''
              type: textarea
          - label: What could they do to improve?
            type: question
            answers:
            - label: ''
              type: textarea
    - label: 'No'
      type: radio
  - label: Was it due to the quality of their application?
    type: question
    answers:
    - label: 'Yes'
      type: radio
      questions:
      - label: Which parts of the application needed improvement?
        type: question
        answers:
        - label: Personal statement
          type: checkbox
        - label: Subject knowledge
          type: checkbox
        - label: 'Other'
          type: checkbox
          questions:
          - label: Please give details
            type: question
            answers:
            - label: ''
              type: textarea
          - label: What could they do to improve?
            type: question
            answers:
            - label: ''
              type: textarea
    - label: 'No'
      type: radio
