name: Review

on:
  push:
    branches: [super-secret-work]

env:
  CF_PROVIDER_VERSION: 0.12.4
  DOCKERHUB_REPOSITORY: dfedigital/apply-for-teacher-training
  PR_NAME: ${{ format('pr-{0}', github.event.number) }}

jobs:
  deploy:
    name: Create review app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Code
      - name: Terraform pin version
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.1

      - name: Set environment variables
        id: set_env_vars
        run: |
          TAG=$(echo $GITHUB_SHA | cut -c1-8)
          echo ::set-env name=TAG::${TAG}

      - name: Terraform deploy
        env:
          TF_VAR_paas_user: ${{ secrets.CF_USERNAME }}
          TF_VAR_paas_password: ${{ secrets.CF_PASSWORD }}
        run: |
          export TF_VAR_paas_app_docker_image=${DOCKERHUB_REPOSITORY}:${TAG}
          export TF_VAR_environment=review-${PR_NAME}
          terraform init -input=false -backend-config="workspace_key_prefix=review:" terraform/app
          terraform workspace select review-${PR_NAME} terraform/app || terraform workspace new review-${PR_NAME} terraform/app
          terraform apply -var-file terraform/workspace-variables/review.tfvars -auto-approve -input=false terraform/app
